# emnify.AmericanEnglish
# Extends Google.Spelling and adds more spelling variations to avoid
extends: existence
message: "In general, use American spelling instead of '%s'."
link: 'https://developers.google.com/style/spelling'
ignorecase: true
level: warning
tokens:
  - '(?:\w+)nised?'
  - '(?:\w+)yse'
  - 'cancell(?:\w+)'
  - 'chequ(?:\w+)'
  - 'favou(?:\w+)'
  - 'fuell(?:\w+)'
  - 'organis(?:\w+)'
  - 'travell(?:\w+)'
  - 'aeroplane'
  - 'analogue'
  - 'appal'
  - 'artefact'
  - 'behaviour'
  - 'calibre'
  - 'catalogue'
  - 'centre'
  - 'characterised?'
  - 'colour'
  - 'cosy'
  - 'criticised?'
  - 'dialogue'
  - 'doughnut'
  - 'endeavour'
  - 'enrol'
  - 'fulfil'
  - 'gramme'
  - 'grey'
  - 'harbour'
  - 'honour'
  - 'humour'
  - 'instalment'
  - 'instil'
  - 'kilogrammes'
  - 'kilometres'
  - 'labour'
  - 'litre'
  - 'manoeuvres'
  - 'metre'
  - 'neighbour'
  - 'odour'
  - 'pretence'
  - 'programme'
  - 'realised?'
  - 'recognised?'
  - 'rigour'
  - 'savour'
  - 'sceptical'
  - 'skilful'
  - 'specialised?'
  - 'standardised?'
  - 'sympathised?'
  - 'unskilful'
  - 'vigour'
