# emnify.WordList
# Extends Google.WordList and applies any exceptions for the emnify Documentation
extends: substitution
message: "Use '%s' instead of '%s'."
link: https://developers.google.com/style/word-list
level: warning
ignorecase: false
action:
  name: replace
swap:
  "(?:API Console|dev|developer) key": API key
  "(?:admin|Admin)": administrator|Administrator
  "(?:cell ?phone|smart ?phone)": phone|mobile phone
  "(?:dev|developer|APIs) console": API console
  "(?:e-mail|E-mail)": email
  "(?:file ?path|path ?name)": path
  "(?:graphql|Graphql|graphQL)": GraphQL
  "(?:inclusive volume|inclusive data volume|data volume)": data allowance
  "(?:ios|IOS)": iOS
  "(?:kill|terminate|abort)": stop|exit|cancel|end
  "(?:OAuth ?2|Oauth)": OAuth 2.0
  "(?:ok|Okay)": OK|okay
  "(?:rate zone|ratezone)": coverage area
  "(?:REST-API|Rest-API|Rest API)": REST API
  "(?:SMSes|SMSs)": SMS
  "(?:subaccounts?|sub-accounts?)": Workspace|Workspaces
  "(?:Superadmin|superadmin|super admin|Super Admin)": SuperAdmin
  "(?:tariff|tariff plan|usage tariff)": data plan
  "(?:two-factor authentication|two factor authentication|multi factor authentication)": multi-factor authentication
  "(?:WiFi|wifi|Wifi)": Wi-Fi
  '[\.]+apk': APK
  '3\-D': 3D
  'Google (?:I\-O|IO)': Google I/O
  "tap (?:&|and) hold": touch & hold
  "un(?:check|select)": clear
  2FA: MFA
  above: preceding
  account name: username
  action bar: app bar
  Ajax: AJAX
  a\.k\.a|aka: or|also known as
  Android device: Android-powered device
  android: Android
  API explorer: APIs Explorer
  approx\.: approximately
  authN: authentication
  authZ: authorization
  autoupdate: automatically update
  cellular data: mobile data
  cellular network: mobile network
  chapter: documents|pages|sections
  check box: checkbox
  CLI: command-line tool
  click on: click|click in
  Container Engine: Kubernetes Engine
  content type: media type
  curated roles: predefined roles
  custom rate zones: custom data plans
  data are: data is
  Developers Console: Google API Console|API Console
  disabled?: turn off|off
  ephemeral IP address: ephemeral external IP address
  evaluation: trial
  evaluation package: trial SIMs
  fewer data: less data
  file name: filename
  firewalls: firewall rules
  functionality: capability|feature
  Googling: search with Google
  grayed-out: unavailable
  hard-coded?: hardcode|hardcoded
  HTTPs: HTTPS
  in order to: to
  inclusive volume \(pooled\): pooled allowance (with shared data)
  inclusive volume \(unpooled\): fixed allowance
  ingest: import|load
  k8s: Kubernetes
  long press: touch & hold
  network IP address: internal IP address
  omnibox: address bar
  open-source: open source
  overage fee: additional usage
  overview screen: recents screen
  pay as you go: pay-per-use
  regex: regular expression
  SHA1: SHA-1|HAS-SHA1
  sign into: sign in to
  SLAs: SLOs
  static IP address: static external IP address
  stylesheet: style sheet
  synch: sync
  tablename: table name
  tablet: device
  tariff profile: coverage policy
  touch: tap
  url: URL
  vs\.: versus
  workspaces?: Workspace|Workspaces
  World Wide Web: web
