extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings'
level: warning
scope: heading
match: $sentence
indicators:
  - ':'
exceptions:
  # General
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - gRPC
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  # emnify
  - emnify Documentation
  - emnify IoT SuperNetwork
  # Glossary
  - AuC
  - DDoS
  - eDRX
  - eUICC
  - eSIM
  - IPsec
  - OpenVPN
  - RESTful API
