name: Validate Content

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.mdx?"

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "./**/*.md*"
          config_file: .markdownlint.jsonc
          ignore_path: .markdownlintignore
